# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde2d6588503f079aebb212522cde74ec5f5348a91144e4a47c203906fa8ed85783f364369918b59b41ac9667552a74bbfd720c51bb5f5ca646df6a177b4b978

test:
  secret_key_base: b2b088d2f3651ceebd0fb71ee9e6265c79ebf2778a3853a2143e8aa0524dad4b3c1c26f348e79b7be1e994a2c7bb7a37aab7d52fe926a65b9ddb7d13ca027b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
